#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd with the required information using the while loop and IFS.

# Using a while loop to read the content of /etc/passwd line by line
while IFS=":" read -r username _ userid groupid _ homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
