#!/bin/bash

# Define the server IP or hostname
server_ip="240202-web-01"

# Specify the private key file
private_key="~/.ssh/school"

# SSH using the private key and user 'ubuntu'
ssh -i "$private_key" ubuntu@"$server_ip"
