#!/bin/bash

# Define the server IP or hostname
server_ip="54.146.94.191"

# Specify the private key file path
private_key="~/.ssh/school"

# SSH using the private key and user 'ubuntu'
ssh -i "$private_key" ubuntu@"$server_ip"
